#!/usr/bin/env bash
# install-node.sh — provision a fresh cf-vpn node end-to-end.
#
# This script:
#   - validates every input the Go installer requires (MODE, NODE_ID, …)
#   - pre-installs cloudflared (Cloudflare apt repo) and lego (go install)
#   - builds AND installs both cfvpnctl and cfvpn-agent
#   - writes the full /etc/cfvpn/cfvpn.env that RunInstall expects
#   - falls back from direct → cloudflare if TCP/443 cannot be bound
#   - upserts node + user into D1 and syncs via agent after install
#   - verifies all systemd units are active before exiting
#
# Usage:
#   sudo -E CF_API_TOKEN=... CF_ACCOUNT_ID=... NODE_ID=us-01 \
#     [NODE_LABEL="US-01 (Dallas)"] [DOMAIN=vpn.example.com] \
#     [USER1_NAME=alice] [MODE=direct] \
#     bash scripts/install-node.sh
#
# NODE_ID  : DNS label (case-insensitive); stored UPPERCASE in D1.
# NODE_LABEL: human-readable name for the panel (defaults to uppercase NODE_ID).
set -euo pipefail

log()  { printf '[install-node] %s\n' "$*"; }
warn() { printf '[install-node] WARN: %s\n' "$*" >&2; }
die()  { printf '[install-node] ERROR: %s\n' "$*" >&2; exit 1; }

require_env() {
  local name="$1"
  [ -n "${!name:-}" ] || die "$name is required"
}

# ----- 0. preflight -----------------------------------------------------------
[ "${EUID:-$(id -u)}" -eq 0 ] || die "run as root (use sudo -E)"
command -v apt-get >/dev/null || die "this script supports Debian/Ubuntu only"

require_env CF_API_TOKEN
require_env CF_ACCOUNT_ID
require_env NODE_ID

: "${USER1_NAME:=user1}"
: "${MODE:=auto}"
: "${DOMAIN:=}"

# Normalize: lowercase for DNS/cfvpnctl, UPPERCASE for D1 storage
NODE_ID="$(echo "$NODE_ID" | tr '[:upper:]' '[:lower:]')"
DB_NODE_ID="$(echo "$NODE_ID" | tr '[:lower:]' '[:upper:]')"

# NODE_LABEL is the panel display name; defaults to DB_NODE_ID if not provided
: "${NODE_LABEL:=$DB_NODE_ID}"

# NODE_ID must be a single DNS label
if ! [[ "$NODE_ID" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]]; then
  die "NODE_ID must be a DNS label: a-z, 0-9, '-', no leading/trailing dash, max 63 chars (got: $NODE_ID)"
fi

# USER1_NAME must match the xray validator: ^[A-Za-z0-9_-]{1,32}$
if ! [[ "$USER1_NAME" =~ ^[A-Za-z0-9_-]{1,32}$ ]]; then
  die "USER1_NAME must match ^[A-Za-z0-9_-]{1,32}\$ (got: $USER1_NAME)"
fi

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[ -f "$PROJECT_ROOT/go.mod" ] || die "go.mod not found; run from inside the cf-vpn repository"

# AGENT_SHARED_SECRET gates /admin/v1/* on the admin tunnel
SECRET_AUTOGENERATED=0
if [ -z "${AGENT_SHARED_SECRET:-}" ]; then
  AGENT_SHARED_SECRET="$(openssl rand -hex 32)"
  SECRET_AUTOGENERATED=1
fi

D1_DB_ID="${CFVPN_D1_DATABASE_ID:-0649f07f-e2c0-47f3-b84a-273f7f67332e}"

# d1_query <jq-built-json> — runs a D1 query; token stays out of argv via --config
d1_query() {
  local payload="$1"
  local tmpf; tmpf="$(mktemp)"; chmod 600 "$tmpf"
  printf '%s' "$payload" >"$tmpf"
  local resp
  resp=$(curl -sS --max-time 30 --config - <<EOF
header = "Authorization: Bearer ${CF_API_TOKEN}"
header = "Content-Type: application/json"
url = "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/d1/database/${D1_DB_ID}/query"
data-binary = "@${tmpf}"
EOF
)
  rm -f "$tmpf"
  echo "$resp"
}

# ----- 1. resolve MODE --------------------------------------------------------
resolve_mode() {
  case "$MODE" in
    direct|cloudflare) return 0 ;;
    auto) ;;
    *) die "MODE must be direct, cloudflare, or auto (got: $MODE)" ;;
  esac
  if (echo >/dev/tcp/127.0.0.1/443) >/dev/null 2>&1; then
    warn "TCP/443 already accepting connections on this host; selecting MODE=cloudflare"
    MODE=cloudflare; return 0
  fi
  if ss -tlnp 2>/dev/null | awk '{print $4}' | grep -qE '(^|:)443$'; then
    warn "Something is already listening on :443; selecting MODE=cloudflare"
    MODE=cloudflare; return 0
  fi
  MODE=direct
}
resolve_mode
log "selected MODE=$MODE"

# ----- 2. OS dependencies -----------------------------------------------------
log "installing OS dependencies"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y

PACKAGES=(curl wget jq openssl uuid-runtime qrencode ca-certificates git iproute2 golang-go ufw tar gzip coreutils bash systemd dnsutils rsync)
TO_INSTALL=()
for pkg in "${PACKAGES[@]}"; do
  if dpkg -s "$pkg" >/dev/null 2>&1; then
    if apt-get --just-print upgrade 2>/dev/null | grep -q "^Inst $pkg "; then
      TO_INSTALL+=("$pkg")
    fi
  else
    TO_INSTALL+=("$pkg")
  fi
done

if [ ${#TO_INSTALL[@]} -gt 0 ]; then
  log "installing/upgrading: ${TO_INSTALL[*]}"
  apt-get install -y "${TO_INSTALL[@]}"
else
  log "all packages already up-to-date"
fi

command -v go >/dev/null || die "go toolchain not on PATH after apt-get install"

if dig @173.245.59.111 cloudflare.com +time=3 +tries=1 >/dev/null 2>&1; then
  log "Cloudflare authoritative DNS reachable"
else
  warn "Cloudflare authoritative DNS unreachable; using recursive DNS propagation checks for lego"
  export LEGO_DISABLE_CP=1
  export LEGO_DNS_RESOLVERS="${LEGO_DNS_RESOLVERS:-1.1.1.1:53,8.8.8.8:53}"
  unset LEGO_PROPAGATION_WAIT
fi

# ----- 2b. pre-install cloudflared via Cloudflare official apt repo -----------
# Pre-installing means cfvpnctl's EnsureCloudflared (binary.Exists check) will
# skip its GitHub download entirely.
if ! command -v cloudflared >/dev/null 2>&1; then
  log "installing cloudflared via Cloudflare apt repo"
  mkdir -p --mode=0755 /usr/share/keyrings
  curl -fsSL https://pkg.cloudflare.com/cloudflare-public-v2.gpg \
    | tee /usr/share/keyrings/cloudflare-public-v2.gpg >/dev/null
  echo 'deb [signed-by=/usr/share/keyrings/cloudflare-public-v2.gpg] https://pkg.cloudflare.com/cloudflared any main' \
    | tee /etc/apt/sources.list.d/cloudflared.list >/dev/null
  apt-get update -y
  apt-get install -y cloudflared
  log "cloudflared installed: $(cloudflared --version 2>&1 | head -1)"
else
  log "cloudflared already installed: $(cloudflared --version 2>&1 | head -1)"
fi

# ----- 2c. pre-install lego via go install (no GitHub API) --------------------
# GOBIN=/usr/local/bin places the binary directly where cfvpnctl expects it.
if ! command -v lego >/dev/null 2>&1; then
  log "installing lego via go install (latest)"
  GOBIN=/usr/local/bin go install github.com/go-acme/lego/v4/cmd/lego@latest
  log "lego installed: $(lego --version 2>&1 | head -1)"
else
  log "lego already installed: $(lego --version 2>&1 | head -1)"
fi

# ----- 3. build & install both binaries ---------------------------------------
log "building cfvpnctl + cfvpn-agent"
(
  cd "$PROJECT_ROOT"
  go build -o bin/cfvpnctl    ./cmd/cfvpnctl
  go build -o bin/cfvpn-agent ./cmd/cfvpn-agent
)
install -m 0755 "$PROJECT_ROOT/bin/cfvpnctl"    /usr/local/bin/cfvpnctl
install -m 0755 "$PROJECT_ROOT/bin/cfvpn-agent" /usr/local/bin/cfvpn-agent

# ----- 4. check zone collision ------------------------------------------------
D1_RESP=$(d1_query "$(jq -n '{sql:"SELECT id,label,zone,vpn_host FROM nodes WHERE zone != ?", params:[""]}')")
D1_OK=$(echo "$D1_RESP" | jq -r '.success // false')
if [ "$D1_OK" != "true" ]; then
  warn "D1 zone check failed (non-fatal): $(echo "$D1_RESP" | jq -r '.errors[0].message // "unknown"')"
else
  D1_ROWS=$(echo "$D1_RESP" | jq '.result[0].results // []')
  NODE_COUNT=$(echo "$D1_ROWS" | jq 'length')
  log "D1 nodes: $NODE_COUNT"
  if [ "$NODE_COUNT" -gt 0 ]; then
    echo "$D1_ROWS" | jq -r 'group_by(.zone) | .[] | "  \(.[0].zone): \(map(.id+"("+.vpn_host+")") | join(", "))"'
  fi
fi

# ----- 5. write env file ------------------------------------------------------
# cfvpnctl reads NODE_ID (lowercase) from env for DNS label use.
# DB_NODE_ID (uppercase) is used only by this script for D1 writes.
log "writing /etc/cfvpn/cfvpn.env"
install -d -m 700 /etc/cfvpn
tmp_env="$(mktemp)"
{
  printf 'CF_API_TOKEN=%s\n'       "$CF_API_TOKEN"
  printf 'CF_ACCOUNT_ID=%s\n'      "$CF_ACCOUNT_ID"
  printf 'NODE_ID=%s\n'            "$NODE_ID"
  printf 'USER1_NAME=%s\n'         "$USER1_NAME"
  printf 'MODE=%s\n'               "$MODE"
  printf 'AGENT_SHARED_SECRET=%s\n' "$AGENT_SHARED_SECRET"
  [ -n "$DOMAIN" ] && printf 'DOMAIN=%s\n' "$DOMAIN"
} >"$tmp_env"
install -m 600 "$tmp_env" /etc/cfvpn/cfvpn.env
rm -f "$tmp_env"

# ----- 6. firewall hygiene ----------------------------------------------------
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q 'Status: active'; then
  log "ufw is active — ensuring SSH is allowed"
  ufw allow OpenSSH || ufw allow 22/tcp || warn "could not whitelist SSH; verify manually"
fi

# ----- 7. run installer -------------------------------------------------------
list_admin_tunnels() {
  curl -sS --max-time 10 --config - <<EOF | jq -r '.result // [] | .[] | select(.name | startswith("cfvpn-admin-")) | "\(.id) \(.name)"' 2>/dev/null || true
header = "Authorization: Bearer ${CF_API_TOKEN}"
url = "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/cfd_tunnel?is_deleted=false&per_page=100"
EOF
}
TUNNELS_BEFORE="$(list_admin_tunnels | sort)"

cleanup_orphan_tunnels() {
  local rc=$?
  [ $rc -eq 0 ] && return 0
  warn "cfvpnctl install exited with status $rc — checking for orphan admin tunnels"
  local tunnels_after new
  tunnels_after="$(list_admin_tunnels | sort)"
  new="$(comm -13 <(printf '%s\n' "$TUNNELS_BEFORE") <(printf '%s\n' "$tunnels_after"))"
  if [ -n "$new" ]; then
    warn "orphan admin tunnels created during failed install:"
    printf '%s\n' "$new" | while read -r tid tname; do
      [ -z "$tid" ] && continue
      warn "  $tid ($tname) — clean up with: sudo cfvpnctl rotate-domain --cleanup $tid --yes"
    done
  fi
  exit $rc
}
trap cleanup_orphan_tunnels EXIT

log "running cfvpnctl install (mode=$MODE)"
cfvpnctl install
trap - EXIT

log "installing healthcheck timer"
cfvpnctl healthcheck install

# ----- 8. verify systemd units ------------------------------------------------
log "verifying systemd units"
units=(cfvpn-xray cfvpn-hysteria cfvpn-cloudflared cfvpn-agent)
sleep 2
for u in "${units[@]}"; do
  state=$(systemctl is-active "$u" || true)
  if [ "$state" = active ]; then
    log "  $u: active"
  else
    warn "  $u: $state — check 'journalctl -u $u -n 80'"
  fi
done

log "running healthcheck"
cfvpnctl healthcheck run || warn "healthcheck reported failure (Cloudflare tunnel may still be registering — re-run in 60s)"

# ----- 9. sync node + user to D1 & control panel -----------------------------
log "syncing $DB_NODE_ID + user $USER1_NAME to D1"

# Load all runtime values written by cfvpnctl install into current shell
# shellcheck source=/dev/null
set -a; . /etc/cfvpn/cfvpn.env; set +a

NOW_MS=$(date +%s%3N)
ZONE="$(echo "$DOMAIN" | rev | cut -d'.' -f1,2 | rev)"

# 9a. Upsert node with full config (INSERT OR REPLACE handles re-installs)
NODE_RESP=$(d1_query "$(jq -n \
  --arg id    "$DB_NODE_ID" \
  --arg label "$NODE_LABEL" \
  --arg ah    "$ADMIN_HOST" \
  --arg vh    "$DOMAIN" \
  --arg hh    "$HY2_HOST" \
  --argjson hp "$HY2_PORT" \
  --arg how   "$HY2_OBFS_PW" \
  --arg ip    "$PUBLIC_IP" \
  --arg zone  "$ZONE" \
  --arg mode  "$MODE" \
  --arg rpk   "$REALITY_PUBLIC_KEY" \
  --arg rsid  "$REALITY_SHORT_ID" \
  --arg rsni  "$REALITY_SNI" \
  --arg rdest "$REALITY_DEST" \
  --argjson ts "$NOW_MS" \
  --arg sec   "$AGENT_SHARED_SECRET" \
  '{
    sql: "INSERT OR REPLACE INTO nodes (id,label,admin_host,vpn_host,hy2_host,hy2_port,hy2_obfs_pw,public_ip,zone,mode,status,reality_pubkey,reality_sid,reality_sni,reality_dest,last_seen_at,latency_ms,created_at,agent_secret) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,null,null,?,?)",
    params: [$id,$label,$ah,$vh,$hh,$hp,$how,$ip,$zone,$mode,"active",$rpk,$rsid,$rsni,$rdest,$ts,$sec]
  }')")
NODE_OK=$(echo "$NODE_RESP" | jq -r '.success // false')
NODE_CHANGES=$(echo "$NODE_RESP" | jq -r '.result[0].meta.changes // 0')
if [ "$NODE_OK" = "true" ] && [ "$NODE_CHANGES" -ge 1 ]; then
  log "node $DB_NODE_ID upserted in D1 (label=$NODE_LABEL, zone=$ZONE)"
else
  warn "node D1 upsert failed: $(echo "$NODE_RESP" | jq -r '.errors[0].message // "unknown"')"
fi

# 9b. Ensure user exists in D1; create with random sub_token if missing
USER_RESP=$(d1_query "$(jq -n --arg uid "$USER1_NAME" \
  '{sql:"SELECT id FROM users WHERE id=?", params:[$uid]}')")
USER_EXISTS=$(echo "$USER_RESP" | jq -r '.result[0].results | length')
if [ "$USER_EXISTS" -lt 1 ]; then
  SUB_TOKEN="$(openssl rand -hex 16)"
  CRE_RESP=$(d1_query "$(jq -n \
    --arg uid "$USER1_NAME" \
    --arg tok "$SUB_TOKEN" \
    --argjson ts "$NOW_MS" \
    '{sql:"INSERT OR IGNORE INTO users (id,name,sub_token,created_at) VALUES (?,?,?,?)", params:[$uid,$uid,$tok,$ts]}')")
  CRE_OK=$(echo "$CRE_RESP" | jq -r '.success // false')
  if [ "$CRE_OK" = "true" ]; then
    log "user $USER1_NAME created in D1 (sub_token=$SUB_TOKEN)"
  else
    warn "user create failed: $(echo "$CRE_RESP" | jq -r '.errors[0].message // "unknown"')"
  fi
else
  log "user $USER1_NAME already in D1"
fi

# 9c. Upsert user_nodes (vless_uuid + hy2_pw from cfvpnctl-generated env)
UN_RESP=$(d1_query "$(jq -n \
  --arg uid   "$USER1_NAME" \
  --arg nid   "$DB_NODE_ID" \
  --arg uuid  "$UUID_USER1" \
  --arg hy2pw "$HY2_PASS_USER1" \
  --argjson ts "$NOW_MS" \
  '{sql:"INSERT OR REPLACE INTO user_nodes (user_id,node_id,vless_uuid,hy2_pw,created_at) VALUES (?,?,?,?,?)", params:[$uid,$nid,$uuid,$hy2pw,$ts]}')")
UN_OK=$(echo "$UN_RESP" | jq -r '.success // false')
if [ "$UN_OK" = "true" ]; then
  log "user_nodes $USER1_NAME → $DB_NODE_ID upserted (uuid=$UUID_USER1)"
else
  warn "user_nodes upsert failed: $(echo "$UN_RESP" | jq -r '.errors[0].message // "unknown"')"
fi

# 9d. Confirm agent is live via admin tunnel sync.
# The agent expects syncUser objects ({name,vless_uuid,hy2_pw}), not bare name
# strings — sending strings fails with "cannot unmarshal string into syncUser".
log "calling agent sync via $ADMIN_HOST"
SYNC_BODY=$(jq -n \
  --arg n "$USER1_NAME" \
  --arg u "$UUID_USER1" \
  --arg p "$HY2_PASS_USER1" \
  '{users:[{name:$n, vless_uuid:$u, hy2_pw:$p}]}')
SYNC_RESP=$(curl -sS --max-time 30 \
  -X POST "https://$ADMIN_HOST/admin/v1/sync" \
  -H "Authorization: Bearer $AGENT_SHARED_SECRET" \
  -H "Content-Type: application/json" \
  -d "$SYNC_BODY" 2>&1) || SYNC_RESP=""
SYNC_OK=$(echo "$SYNC_RESP" | jq -r '.ok // false' 2>/dev/null || echo false)
if [ "$SYNC_OK" = "true" ]; then
  log "agent sync OK — $(echo "$SYNC_RESP" | jq -r '.users') user(s) active on node"
else
  warn "agent sync non-OK: $SYNC_RESP"
fi

log "node ready: $DB_NODE_ID ($NODE_LABEL)"
log "next: sudo cfvpnctl status"
log "next: sudo cfvpnctl gen-sub $USER1_NAME"
